Repository DIT112-V21/group-08, pull requests merged in 2021-05, with the labels that each got.

#39 GUI PyQt5 voice recognition
  .github/workflows/python-build-yml
  .idea/.gitignore
  .idea/group-08.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  GUI Pycharm/Dialogflow.py
  GUI Pycharm/Exceptions.py
  GUI Pycharm/GUI_Pathfinder.py
  GUI Pycharm/brakes.png
  GUI Pycharm/design.py
  GUI Pycharm/help.png
  GUI Pycharm/history.png
  GUI Pycharm/logBackup.txt
  GUI Pycharm/private_key.json
  GUI Pycharm/record.png
  GUI Pycharm/voice.png
Labels: Sprint 3

#44 Documentation Purpose
  GUI Pycharm/Help Window.png
  GUI Pycharm/Main window.png
  GUI Pycharm/Path Finder.png
  GUI Pycharm/Voice Control Window.png
  README.md
Labels: documentation

#45 More Preview Content
  GUI Pycharm/Help Window.png
  GUI Pycharm/Python Libraries.png
Labels: documentation

#46 Updated README file version
  README.md
Labels: documentation

#47 GUI py qt voice recognition
  .idea/group-08.iml
  .idea/misc.xml
  GUI Pycharm/Brake.png
  GUI Pycharm/GUI_Pathfinder.py
  GUI Pycharm/Power.png
  GUI Pycharm/brakes.png
  GUI Pycharm/design.py
  GUI Pycharm/help icon.png
  GUI Pycharm/how to use.png
  GUI Pycharm/logBackup.txt
Labels: Sprint 4

#51 Unified Arduino Sketches
  arduino/smartcar/smartcar.ino
Labels: Sprint 4

#54 GUI py qt voice recognition
  GUI Pycharm/GUI_Pathfinder.py
Labels: Sprint 4
