Repository DIT112-V21/group-08, pull requests merged in 2021-04, with the labels that each got.

#9 Finished manual controls with speed control
  arduino/smartcar/smartcar.ino
Labels: Sprint 1

#18 Update README.md
  README.md
Labels: documentation

#22 Added source files for ios App project
  SMCE Remote/Assets.xcassets/AccentColor.colorset/Contents.json
  SMCE Remote/Assets.xcassets/AppIcon.appiconset/Contents.json
  SMCE Remote/Assets.xcassets/Contents.json
  SMCE Remote/Assets.xcassets/map.imageset/Contents.json
  SMCE Remote/Assets.xcassets/map.imageset/this.png
  SMCE Remote/Assets.xcassets/paths.imageset/Contents.json
  SMCE Remote/Assets.xcassets/paths.imageset/Paths.svg
  SMCE Remote/Assets.xcassets/smceLogo.imageset/Contents.json
  SMCE Remote/Assets.xcassets/smceLogo.imageset/SMCE Logo.png
  SMCE Remote/Info.plist
  SMCE Remote/MQTT/SMCEMQTT.swift
  SMCE Remote/Model/Astar.swift
  SMCE Remote/Model/NoWalk.swift
  SMCE Remote/Model/Node.swift
  SMCE Remote/Model/PathFinder.swift
  SMCE Remote/Model/SwiftPriorityQueue.swift
  SMCE Remote/Model/Waypoint.swift
  SMCE Remote/OLD/ContentViewOld.swift
  SMCE Remote/OLD/GridViewOLD.swift
  SMCE Remote/OLD/MQTTViewOld.swift
  SMCE Remote/OLD/MQTTtest.swift
  SMCE Remote/Preview Content/Preview Assets.xcassets/Contents.json
  SMCE Remote/SMCE_RemoteApp.swift
  SMCE Remote/Tests/Graph.swift
  SMCE Remote/Tests/SimpleNode.swift
  SMCE Remote/Tests/SortedArray.swift
  SMCE Remote/Tests/Step+Comparable.swift
  SMCE Remote/Utils/Funcs.swift
  SMCE Remote/View/ContentView.swift
  SMCE Remote/View/ContentViewNOTUSED.swift
  SMCE Remote/View/GridView.swift
  SMCE Remote/View/WaypointView.swift
Labels: Sprint 2
